module.exports = {
    USERNAMES_COLLECTION: "usernames",
    GAME_COLLECTION: "games",
    LOBBY_RESOURCE: "lobby",
    MATCH_RESOURCE: "lobby",
    USER_COLLECTION: "users",
    FRIENDS_COLLECTION: "friends",
    FRIENDS_CODES_COLLECTION: "friend_codes",
    REQUESTS_FRIEND: "friend",
    REQUESTS_GAME: "game",
    REQUEST_ACCEPT_FRIEND: "friend_accept",
    REQUEST_ACCEPT_GAME: "game_accept",
    FAMILY_COLLECTION: "families",
    MEMORIES_COLLECTION: "memories",
    MEMOS_COLLECTION: "memos",
    NUMBERS_COLLECTION: "numbers",
    CAREGIVERS_COLLECTION: "caregivers",
    CHAT_COLLECTION: "chats",
    patient: 0,
    family: 1,
    caregiver: 2,
};